version: '3'

services:
    db:
        image: mysql:5.7.29
        volumes:
            - ./.mysql-data/db:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=whee
            - MYSQL_DATABASE=users_service
            - MYSQL_USER=users-service
            - MYSQL_PASSWORD=blah
    web:
        build: .
        ports:
          - 8080:8080
        depends_on:
          - db
        restart: on-failure
        environment:
            - PORT=57544
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DIALECT=mysql
            - DB_NAME=users_service
            - DB_USERNAME=users-service
            - DB_PASSWORD=blah
